const localizations = [];

localizations["he"] = [];
const hebrew = localizations["he"];
hebrew["kapot"] = "בית כנסת כפות תמרים"
hebrew["address"] = "הציפורן 5, אפרת"
hebrew["date"] = 'אלול, תשפ"ג'
hebrew["dear"] = 'משפחת כפות תמרים היקרה,'
hebrew["intro"] = 'לקראת ראש השנה הבא עלינו לטובה, אנו מאחלים לכולם שנה של בריאות, אושר וצמיחה רוחנית, כיחידים וביחד כקהילה. אנו גם רוצים לנצל את ההזדמנות לברך את כל אלה שהצטרפו לאחרונה לשכונה! אנו מקווים שתמצאו בבית הכנסת משפחה שנייה וחמה.'
hebrew["outstanding"] = 'עם סגירת השנה, אנו מבקשים מכל החברים הנוכחיים לדאוג לכל התחייבות לבית הכנסת (תשלום עבור קידוש או אגרות או אגרות קודמים וכו׳) באמצעות <a href="https://ktefrat.org.il/donate/" target="_blank">קישור זה</a>. תודה!'
hebrew["membershipTitle"] = "חֲבֵרוּת"
hebrew["fees"] = "דמי חברות הן כדלקמן:"
hebrew["membershipFeeFull"] = "חברי קרן בנין: <strong>800&#8362;</strong> (למשפחה)"
hebrew["membershipFeePartial"] = "חברים שנתיים: <strong>1,100&#8362;</strong> (למשפחה)"
hebrew["membershipFeeWeekday"] = "תפילות ימי חול (ללא חברות): <strong>500&#8362;</strong>"
hebrew["infoForm"] = 'כל החברים, החדשים והוותיקים מתבקשים למלא <a href="https://ktefrat.org.il/memberform/" target="_blank">טופס זה</a> אם טרם עשו זאת.'
hebrew["negotiable"] = 'נשמח לקבל אותכם כחברים בקהילה שלנו. במידה ויש לכם אילוצים כספיים, אפשר לדבר עם רפי אייז (<a href="mailto:rafieis@gmail.com" target="_blank">rafieis@gmail.com</a>)  בסודיות.'
hebrew['buildingFundHeader'] = 'קרן בנין'
hebrew['buildingFundAmount'] = 'קרן בנין היא <strong>3,600&#8362;</strong>. תשלומי קרן בנין יכולים להתבצע בתשלומים, במינימום של 360 ₪ לשנה. אפשר לבצע תשלומים לקרן בנין <a href="https://www.jgive.com/new/en/ils/donation-targets/103156" target="_blank">בקישור זה</a>.'
hebrew['seating'] = 'מקומות ישיבה לימים נוראים'
hebrew['terms'] = 'החברות כוללת מקומות ישיבה לבני המשפחה הקרובים. מקומות ישיבה לילדים נשואים, הורים, סבים וסבתות ואורחים אחרים הם <strong>150&#8362;/מושב</strong> לימים נוראים ו-<strong>100&#8362;/מושב</strong> לראש השנה או ליום כיפור. מקומות ישיבה נוספים תלויים בזמינות. מקומות ישיבה לילדים מתחת לכיתה ה׳ יהיו בהתאם לזמינות.'
hebrew['deadline'] = 'להזמין מקומות יש למלא את טופס גוגל או אם אינכם יכולים, את הטופס הכתוב המצורף כאן, עד יום שלישי, 5 בספטמבר, 2023 / י״ט אלול.'
hebrew['methods'] = 'תשלום דמי שנתי ותוספת מקומות ישיבה ניתן לבצע באחת מהדרכים הבאות:'
hebrew['methodJGive'] = '<strong>מועדף</strong>: אתר הבית כנסת (JGive): <a href="https://ktefrat.org.il/donate/" target="_blank">https://ktefrat.org.il/donate/</a>'
hebrew['methodBank'] = 'העברה בנקאית:'
hebrew['accountName'] = 'שם חשבון: בית הכנסת כפות תמרים'
hebrew['bankName'] = 'בנק: מזרחי 20'
hebrew['branch'] = 'סניף: אפרת 454'
hebrew['accountNumber'] = 'מספר חשבון: 149924'
hebrew['check'] = "צ'ק לכפות תמרים"
hebrew['thanks'] = 'תודה מראש על התייחסותכם המהירה לעניין זה.'
hebrew['signature'] = 'ועד מנהל של כפות תמרים והגבאים'
hebrew['requests'] = 'בקשות למושבים בימים נוראים'
hebrew['nameTitle'] = 'שם'
hebrew['emailTitle'] = 'מייל'
hebrew['memberTitle'] = 'מצב חברות'
hebrew['fullMember'] = 'קרן בנין שולם; משלם דמי חברות שנתיים'
hebrew['becomingFullMember'] = 'קרן בנין טרם שולם; משלם אותו כעת עם דמי חברות שנתיים'
hebrew['partialMember'] = 'משלם דמי חברות שנתיים, אבל לא קרן בנין'
hebrew['notAMember'] = 'עוד לא מצטרף לחברות בית הכנסת'
hebrew['numDavenersTitle'] = 'סה״כ מתפללים במשך ימים נוראים'
hebrew['contact'] = 'לשאלות או הערות, נא ליצור קשר עם <a href="mailto:ktefrat@gmail.com" target="_blank">ktefrat@gmail.com</a>.'
hebrew['davenerTitleStart'] = 'מתפלל #'
hebrew['maleLabelX'] = 'זכר'
hebrew['femaleLabelX'] = 'נקבה'
hebrew['optionType'] = 'קטגוריה'
hebrew['optionMember'] = 'חבר'
hebrew['optionYoungKid'] = 'ילד מתחת לכיתה ה׳'
hebrew['optionOldKid'] = 'ילד - כיתה ה׳ ומעלה'
hebrew['optionGuest'] = 'ילד נשוי / אורח'
hebrew['roshHaShanahLabelX'] = 'ראש השנה'
hebrew['yomKippurLabelX'] = 'יום כיפור'
hebrew['due'] = 'לתשלום:'
hebrew['totalsDue'] = 'סכומים לתשלום'
hebrew['eachLink'] = 'נא לשלם כל סכום בקישור המתאים.'
hebrew['membershipDueLabel'] = 'דמי חברות'
hebrew['buildingFundDueLabel'] = 'קרן בנין'
hebrew['seatsDueLabel'] = 'תשלום למושבים'
hebrew['submitButton'] = 'שלח'
hebrew['name'] = 'שם'
hebrew['optionGrade'] = 'כיתה'
hebrew['optionGan'] = 'גן'
hebrew['optionFirst'] = 'א׳'
hebrew['optionSecond'] = 'ב׳'
hebrew['optionThird'] = 'ג׳'
hebrew['optionFourth'] = 'ד׳'